### ISSUE TITLE
Not able to attach vREPL or re-run "Run" after "Run current file"

### ISSUE THREAD

**Issue by laurencepike** [paulober/MicroPico#100]
Using VS Code Remote SSH - Host on Rasbian OS 32bit (RPI 4B), client Windows 11
Rasbperry Pi set up using the wiki (serial port enabled with login shell disabled)

## What are the steps to reproduce this issue?
1. Open picowgo project, see "Pico Connected"
2. Click "Run" or cntrl+shift+P "Pico-W-Go > Run current file"

## What happens?
Code is uploaded and runs on Pico W (yay)
Notification pops up: "Pico vREPL not open" (maybe oh no?)
"✔️ Pico Connected " in bottom bar

From this point forward I cannot attach vREPL and if I click "Run"/cntrl+shift+P "Pico-W-Go > Run current file" nothing happens

If I physically disconnect the pico usb and reconnect then I can "Run" new code again (one time, like back to the start).

If vREPL is open before I run "Run" for the first time, then "None" is printed in the terminal and then becomes unresponsive

## What were you expecting to happen?
vREPL to open and being able to continue to click "Run" as I update my code

## Any logs, error output, etc?
Protcoll is not listed in output options

## Any other comments?
If this is intended behavior, or something I'm unfamiliar with on the Pico W, very sorry for the inconvenience. I'm not yet very familiar with embedded systems development

## Support info

Copy this from the `Help -> Info/About -> Copy` option in Visual Studio Code:

```
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```
(Note that this is using vscode remote ssh, another bug raised said it was not working, it's working for me minus having to unplug my pico after every code run, not sure if this particular issue is specific to this environment)

**Comment by paulober** [comment]
Maybe the problem is related to remote ssh vscode integration like an other issue reports. Does the issue sill persists after v3.0.11?

**Comment by martinowitsch** [comment]
I've got the same issue. Device gets connected, I can run code, but I cant get any output in my terminal and got this warning:

![grafik](https://github.com/paulober/Pico-W-Go/assets/37714509/3753da56-dbbd-412d-83bb-39a5be40c9d0)

VisualStudioCode Version: 1.79.0
Python: 3.11.3
Pico-W-Go: 3.0.12
Pyserial: 3.5

**Comment by brehor** [comment]
I ran into this issue as well.
I found that if I was in the Workspace created by Pico-W-Go when the virtual file system is activated, the vREPL would not open. If I close the workspace and open the folder, everything works normally.

Steps to reproduce:
1. open a configured folder **File>Open Folder**
The vREPL auto opened and is operational.
![image](https://github.com/paulober/Pico-W-Go/assets/18555697/46f4bbb0-c1cf-439b-a2fa-aaa4fb25a4fa)

2. Click `Toggle Pico-W-FS`
![image](https://github.com/paulober/Pico-W-Go/assets/18555697/366339d9-b67f-43a5-9f47-b6e8cf1cbc1a)

3. If the REPL is still open, it still works
![image](https://github.com/paulober/Pico-W-Go/assets/18555697/e55a213c-bd54-4f23-a376-da1646cac744)

4. If I close the REPL and run the program, I get the error
![image](https://github.com/paulober/Pico-W-Go/assets/18555697/e728c1d9-b1de-40a8-a9af-03b9674616d9)

5. I can no longer open the REPL from there until I open the folder once again.

**Comment by paulober** [comment]
@laurencepike Does the issue still exists for you.
I tried following steps:
- Install remote ssh extension on desktop
- Connect to headless Raspberry Pi (with remote ssh)
- It installs the vscode server and sets up vscode
- Install the Pico-W-Go extension on the target raspberry pi
- Open new folder > run configure project
- I connects to the Pico connected to the raspberry pi without any problems 
- When I try to run a file it says vREPL not open
- New Terminal > vREPL
- vREPL opens normally and I can not hit the run button again and it runs

**Comment by paulober** [comment]
@martinowitsch New Terminal > Pico (W) vREPL

**Comment by laurencepike** [comment]
I just tried again using the steps provided by @brehor and was able to get the vREPL open after toggling the Pico-W-FS (toggling the workspace caused my connection to ssh vscode to need to reload). After that I was able to see vREPL fine, and run/stop code as expected.

**Comment by paulober** [comment]
@laurencepike Your issue should be resolve with the release of v3.1.0, can you confirm?

**Comment by paulober** [comment]
Closed due to inactivity
