### ISSUE TITLE
Bottom control bar missing in full screen (w11)

### ISSUE THREAD

**Issue by netchkin** [paulober/MicroPico#122]
> When I configure the project in a non-maximized window, the bottom bar is visible:
![image](https://github.com/paulober/MicroPico/assets/2874685/9a966f8c-ab9b-4022-923c-e5381499c946)
> When I maximize the window, the bar is not visible.
![image](https://github.com/paulober/MicroPico/assets/2874685/62c0a857-f149-48fb-8316-037ac963ff55)

## What are the steps to reproduce this issue?
1. Have the window not maximized
2. Configure the project for MicroPico
3. Maximize the window

## What happens?
The bottom picow control bar disappears

## What were you expecting to happen?
The bottom pocow control bar stays visible

## Which version of MicroPico are you using?
v3.2.1

## Support info

Copy this from the `Help -> Info/About -> Copy` (`Code -> About Visual Studio Code -> Copy` on macOS) option in Visual Studio Code:

```
Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by paulober** [comment]
That has nothing to do with the extension but with Visual Studio Code. Even if I want I could not hide the status bar via the VS Code api.
