### ISSUE TITLE
Bluetooth support for auto-completion

### ISSUE THREAD

**Issue by montanag** [paulober/MicroPico#129]
# Feature Request 🚀

## Is your feature request related to a problem? Please describe.
When writing bluetooth code for the pico w, the bluetooth module is not recognized by the extension.
<img width="435" alt="Screenshot 2023-08-28 at 10 09 31 PM" src="https://github.com/paulober/MicroPico/assets/34070761/af9c7e7d-a6ad-40dd-b071-21a9d80275b8">

## Describe the solution you'd like
Ideally, the import and it's methods etc would be recognized.

## Describe alternatives you've considered
Considered trying to write out a stub file in the `.vscode/Pico-W-Stub/stubs/` directory.

## Teachability, Documentation, Adoption, Migration Strategy
As mentioned, the auto-complete is based off of [rp2-pico-w-20230426-v1.20.0.uf2](https://micropython.org/resources/firmware/rp2-pico-w-20230426-v1.20.0.uf2). This firmware doesn't seem to support bluetooth connectivity like [this one](https://datasheets.raspberrypi.com/soft/micropython-firmware-pico-w-130623.uf2) does.

**Comment by paulober** [comment]
Will be updated in an upcoming release.

**Comment by montanag** [comment]
Fantastic! Any issues or anything I can subscribe to other than this one? Will it also support libraries like `aioble`? Thanks!

**Comment by paulober** [comment]
The extension is now updated to the current beta firmware. Notice that the auto-completion for bluetooth and aioble are still in an unstable state like the firmware. They can change from day to day or there are errors. If you find a bug please report them in the [Pico-W-Stub](https://GitHub.com/paulober/Pico-W-Stub) repo.

**Comment by montanag** [comment]
Wow, very fast turn around on this. Thank you, and can't wait to play around with the new update
