### ISSUE TITLE
Unable to connect to PICO on VSCODE

### ISSUE THREAD

**Issue by espressocoderepeat** [paulober/MicroPico#130]
> Please provide a clear and concise description of the bug along with logs
Unable to connect to PICO via VSCODE on Windows 11 Home. 
## What are the steps to reproduce this issue?
1. Downloaded Micropython, flashed on PICO device
2. Unplugged and replugged the device
3. VSCODE - Installed MicroPico, Configure Project (went successfully), but can't connect to Pico. Bottom bar says device disconnected all the time. I hit it several times, but to vain.

## What happens?
I can't connect to Pico. Bottom bar says device disconnected all the time. I hit it several times, but to vain. verified COM3 shows up in the device manager.
Also able to use Thonny to connect to the same device without any issues.

## What were you expecting to happen?
Be able to connect to Pico successfully

## Any logs, error output, etc?
*(To get extension logs see Terminal > Output > Extension Host and copy output concerning pico-w-go)*
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

Pico Disconnected, No COM device found.

Tried adding this to .micropico.json but no change in the output
{
    "info": "This file is just used to identify a project folder.",
    "port": "COM3"
}

Tried adding this to .vscode/settings.json but no change in the output
    "micropico.pythonPath": "/c/Users/myname/AppData/Local/Microsoft/WindowsApps/python3",
    "micropico.manualComDevice": "COM3"

## Which version of MicroPico are you using?
RPI_PICO-20230426-v1.20.0.uf2 -> micropython version
v3.2.4 -> MicroPico version

## Support info

Copy this from the `Help -> Info/About -> Copy` (`Code -> About Visual Studio Code -> Copy` on macOS) option in Visual Studio Code:

```
VS Code verison
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by EduardoOliveira** [comment]
I'm experiencing the same behavior, any workaround?
This setup and device works in another Windows machine
