### ISSUE TITLE
Support stopping execution with VSCode command (in addition to the status bar button)

### ISSUE THREAD

**Issue by eplusx** [paulober/MicroPico#134]
# Feature Request 🚀

## Is your feature request related to a problem? Please describe.
Yes. When I switched the IDE from Thonny to VSCode + MicroPico, I had trouble stopping a running program.
* Thonny provides a button/menu item like "Stop/Restart backend" or "Interrupt execution" which work as expected.
* In MicroPico, I tried to find something similar from the command palette. But neither "MicroPico: Reset > Hard" nor "MicroPico: Reset > Soft" worked. No command named "stop..." or "interrupt..." was found. The only remedy I came up with was to remove the Pico's cable, which is not so useful.

Reading this repo, I found the status bar's "Stop" button does the trick by sending Ctrl+C to the board. But that command `micropico.universalStop` is not exposed in the command palette, and thus I can't assign a key binding.

## Describe the solution you'd like
Expose `micropico.universalStop` as a VSCode command "MicroPico: Stop execution".

One drawback is that a list of commands grow by one. But I think this command is worth having as it is critical to Pico programs with an infinite message loop.

## Describe alternatives you've considered
- Advertise the "Stop" status bar button: extend the Getting Started guide.
- Use the status bar button by leaving the keyboard and use a mouse.
  - I'm too lazy to adopt this. :)

## Teachability, Documentation, Adoption, Migration Strategy
- Extend the Getting Started guide: add the common workflow of development with MicroPico.

**Comment by paulober** [comment]
Good idea, hadn't thought about it, but now it seems obvious that this is a necessary update. Thanks for creating this detailed issue and creating a PR for it.
