### ISSUE TITLE
Extension crashes since v3.4.0

### ISSUE THREAD

**Issue by CR1337** [paulober/MicroPico#151]
Since version 3.4.0 the extension crashes when opening VSCode. It does not connect to the raspberry. When trying to execute any MicroPython command using **[Ctrl] + [Shift] + [P]** the extension tries to restart (see status bar at the bottom) but crashes again.

## What are the steps to reproduce this issue?
1. Open an existing MicroPico project with VSCode
2. Try to run a MicroPico command e.g. `MicroPico: Upload current file to Pico`

## What happens?
The extension crashes at startup and when trying to reactivate after executing a command.

## What were you expecting to happen?
The extension should connect to the raspberry at startup and execute commands without crashing.

## Any logs, error output, etc?
*2023-10-19 17:28:48.893 [info] ExtensionService#_doActivateExtension paulober.pico-w-go, startup: true, activationEvent: 'workspaceContains:.micropico'*

*2023-10-19 17:29:06.140 [error] Error: spawn /home/*****/.vscode/extensions/paulober.pico-w-go-3.4.0-linux-x64/dist/scripts/wrapper_linux_amd64/wrapper_linux_amd64.bin EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)*

## Which version of MicroPico are you using?
**v3.4.0**

## Support info

```
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-10027-tuxedo snap
```

**Comment by paulober** [comment]
See #144
