### ISSUE TITLE
could not add/install external modules to the extension

### ISSUE THREAD

**Issue by stan742** [paulober/MicroPico#163]
> Please provide a clear and concise description of the bug along with logs

## What are the steps to reproduce this issue?
1. I put a module in Pico W Stub folder, when I import it in a other file , it said Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named '     '
2.then I try to install through mip ,it is not working as well
3.

## What happens?

I put a module in Pico W Stub folder, when I import it in a other file , it said Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named '     '
2.then I try to install through mip ,it is not working as well
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'mip'

## What were you expecting to happen?
be able to import external library /module for pico

## Any logs, error output, etc?
*(To get extension logs see Terminal > Output > Extension Host and copy output concerning pico-w-go or micropico)*
*(If it’s long, please paste to https://gist.github.com and insert the link here)*
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named '     

## Which version of MicroPico are you using?
MicroPico W v3.4.3

## Support info

Copy this from the `Help -> Info/About -> Copy` (`Code -> About Visual Studio Code -> Copy` on macOS) option in Visual Studio Code:

```
<paste here>
```

**Comment by paulober** [comment]
1. The module must be present on the Pico as well. The file in Pico-W-Stub is only for auto-completion locally.
2. Issues with mip and MicroPython are not related to this project
