### ISSUE TITLE
Have an option to disable auto-updating of the micropython-**-stubs 

### ISSUE THREAD

**Issue by Josverl** [paulober/MicroPico#164]
# Option to Enable/Disable auto-updating of the micropython-**-stubs 🚀

The issue is that I need to / want to use a different version of the stubs than the included version.

If I change for a different version, or board , or port, for instance for a project for an older firmware version, or when I want to make  improvements to the stubs then: 
 - the stubs in `.vscode/Pico-W-Stubs` are overwritten
 - if I install different stubs in the `typings` folder , and change the configuration to use those,
 - I find that  the settings in `.vscode/settings.json` are reverted back to point to : .vscode/Pico-W-Stubs

## Describe the solution you'd like
I'd like control over : 
- whether or not to update the stubs ( default = Yes makes sense for early adopters) 
- whether or not to update the settings for `python.analysis.typeshedPaths` and `python.analysis.extraPaths`

**Comment by paulober** [comment]
Thanks for the report. The next release will stop auto-updating the settings.json as this was only a temporary workaround for the extensions' name-change.
The new `Switch Stubs` command adds the ability to switch the project stubs between RPi Pico, RPi Pico W and ESP32 ports of your stubs. I may add all your ports later.
