### ISSUE TITLE
how to build and test project ?

### ISSUE THREAD

**Issue by benoitLecuppe** [paulober/MicroPico#169]
Bonjour,

I fork the repository.
Download on my Windows PC,
try npm install with some errors :
'''
PS D:\repos\MicroPico\MicroPico> npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pico-w-go@3.5.0',
npm WARN EBADENGINE   required: { vscode: '^1.82.0', node: '>=18.15.0' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '9.6.4' }
npm WARN EBADENGINE }
npm notice
npm notice New major version of npm available! 9.6.4 -> 10.2.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.4
npm notice Run npm install -g npm@10.2.4 to update!
npm notice
npm **ERR!** code E401
npm **ERR!** 401 Unauthorized - GET https://npm.pkg.github.com/download/@paulober/pyboard-serial-com/2.0.5/37da505ae921ad14a4c227c6b99c87856f29653b - authentication token not provided

npm ERR! A complete log of this run can be found in: C:\Users\Benoit\AppData\Local\npm-cache\_logs\2023-11-28T18_13_28_117Z-debug-0.log    
PS D:\repos\MicroPico\MicroPico> scripts/package.ps1
Remove-Item: D:\repos\MicroPico\MicroPico\scripts\package.ps1:2:1
Line |
   2 |  Remove-Item -R .\dist\*
     |  ~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'D:\repos\MicroPico\MicroPico\dist' because it does not exist.

Need to install the following packages:
  vsce@2.15.0
Ok to proceed? (y) y
npm WARN deprecated vsce@2.15.0: vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead.
Executing prepublish script 'npm run vscode:prepublish'...

> pico-w-go@3.5.0 vscode:prepublish
> npm run package

> pico-w-go@3.5.0 package
> rollup -c --environment BUILD:production --sourcemap hidden && npm run compile-uninstaller

'rollup' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
 **ERROR**  npm failed with exit code 1
'''

and Then ?
how can i resolve npm install error ?
how compile the project after small modification of  activator.mts ?
how to debug or test ?

Cordialement,  ;-)
Benoit

**Comment by paulober** [comment]
You need at least Node.JS `18.15.0` (you have installed `v18.13.0`).
For installing all required packages with npm you also need to authenticate your npm with the GitHub NPM registry.

Find more detail in [CONTRIBUTING.md](https://github.com/paulober/MicroPico/blob/main/CONTRIBUTING.md)

You can debug the extension in vscode -> debug side-panel.

Paul
