### ISSUE TITLE
Documentation mentions sync button. But... where is the sync button?

### ISSUE THREAD

**Issue by MarByteBeep** [paulober/MicroPico#172]
Docs mention the following sentence:

`micropico.syncFolder:` This folder will be uploaded to the pyboard when using the sync button.

However I cannot seem to find a dedicated sync button in the UI. There is an "Upload project to Pico" command in the command pallette, but I'm not sure if that's meant by it.

Please clarify what is meant with the sync button.

**Comment by paulober** [comment]
You're right, that's a left-over from a previous revision. As for additional buttons, you can enable them by adding to `micropico.statusbarButtons` setting.
