### ISSUE TITLE
Extension not working 

### ISSUE THREAD

**Issue by SquaredHedghehog** [paulober/MicroPico#192]
I downloaded the extension with the required other extensions but I don't even see the "pico connected" or "pico disconected" text I think something is wrong with my vs code because I tried reinstalling micropython on my pico w many times

**Comment by paulober** [comment]
You first need to open a folder in vs code and run the "MicroPico > Configure Project" command from your command palette: 'CTRL-Shift-P' or 'Cmd-Shift-P' to start a new Micropython project.

**Comment by paulober** [comment]
@SquaredHedghehog did this help?
