### ISSUE TITLE
Uploading a file to Pico with spaces in its name - explorer does't show file

### ISSUE THREAD

**Issue by le-avion** [paulober/MicroPico#220]
> Please provide a clear and concise description of the bug along with logs

## What are the steps to reproduce this issue?
1. Create a python program having one or more spaces in its name
2. select from the explorer or by right clicking in the editor window and selecting "Upload current file to pico"

## What happens?
File is uploaded but not visible in explorer's Pico (W) Remote Workspace.

## What were you expecting to happen?
I was expecting for the file to be visible in the explorer.

## Any logs, error output, etc?
*(To get extension logs see Terminal > Output > Extension Host and copy output concerning pico-w-go or micropico)*
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

## Any other comments?
If I use Thonny I can see the uploaded file just fine. I can also upload this file using Thonny but it isn't visible in VS Code.

## Which version of MicroPico are you using?
3.7.6

## Support info

Copy this from the `Help -> Info/About -> Copy` (`Code -> About Visual Studio Code -> Copy` on macOS) option in Visual Studio Code:

```
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.0-76060800daily20240311-generic
```

**Comment by paulober** [comment]
Thanks for reporting. Will be fixed in next patch today.
