### ISSUE TITLE
RP2040 NeoPixel `__setitem__` is missing

### ISSUE THREAD

**Issue by DeflateAwning** [paulober/MicroPico#264]
The NeoPixel example from the [MicroPython rp2 docs](https://docs.micropython.org/en/latest/rp2/quickref.html) is as follows:

```python
from machine import Pin
from neopixel import NeoPixel

pin = Pin(0, Pin.OUT)   # set GPIO0 to output to drive NeoPixels
np = NeoPixel(pin, 8)   # create NeoPixel driver on GPIO0 for 8 pixels
np[0] = (255, 255, 255) # set the first pixel to white
np.write()              # write data to all pixels
r, g, b = np[0]         # get first pixel colour
```

The example gives a warning on the `np[0] = (255, ...)` line, because it can't find the `__setitem__` method of the `NeoPixel` class.

**Comment by DeflateAwning** [comment]
Ah oops, I totally opened that on the wrong repo; my bad. Thanks a lot!

**Comment by maxi07** [comment]
Just found this issue, hope this will get updated soon!

**Comment by Josverl** [comment]
Please add your vote on the micropython-stub* repo to give me better visibility on these and other improvements on stubs.
